version: '3.8'

networks:
  default:
    name: ${APPLICATION_DOMAIN}
    driver: bridge

services:

  cloud-media-server:
    image: ${DOCKER_REGISTRY-}mrcp-api:${PRODUCT_VERSION-}
    restart: ${RESTART_POLICY-unless-stopped}
    environment:
      MEDIA_SERVER__DEPLOYMENT_ID: "${MEDIA_SERVER__DEPLOYMENT_ID}"
      MEDIA_SERVER__NUM_CHANNELS: "${MEDIA_SERVER__NUM_CHANNELS}"
      MEDIA_SERVER__SERVER_IP: "${MEDIA_SERVER__SERVER_IP}"
      MEDIA_SERVER__LUMENVOX_API_ADDRESS: "${MEDIA_SERVER__LUMENVOX_API_ADDRESS}"
      MEDIA_SERVER__LUMENVOX_API_PORT: "${MEDIA_SERVER__LUMENVOX_API_PORT}"
      MEDIA_SERVER__LOGGING_LEVEL: "${MEDIA_SERVER__LOGGING_LEVEL}"
      CDR_FILE_MAX_MB: "5"
      CDR_FILE_MAX_BACKUPS: "3"
      TZ: "${CONTAINER_TIMEZONE}"
    ports:
      - "554:554/tcp"
      - "5060-5061:5060-5061/tcp"
      - "5060-5061:5060-5061/udp"
      - "20000-20200:20000-20200/tcp"
      - "25000-25200:25000-25200/udp"
    volumes:
      - ./certs:/certs
      - ./logs:/var/log/lumenvox/
      - ./waveforms:/var/lumenvox/waveforms
      - ./management_certs:/var/lumenvox/certs
      - ./credentials/credentials.ini:/credentials/credentials.ini
    extra_hosts:
      - "${MEDIA_SERVER__HOST_MAP:-placeholder:127.0.0.1}"
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
